TensorFlow is an open-source machine learning framework developed by Google. It’s widely used for numerical computation and building machine learning models, particularly deep learning models. TensorFlow is highly flexible and can run on various platforms, including CPUs, GPUs, and TPUs, making it a powerful tool for both research and production.

Key Concepts Tensors:

Definition: Tensors are the fundamental building blocks in TensorFlow, representing multi-dimensional arrays. Rank: The number of dimensions a tensor has (e.g., a scalar has rank 0, a vector rank 1, a matrix rank 2). Shape: The dimensions of the tensor, represented as a tuple (e.g., a 3x4 matrix has a shape of (3, 4)).

In [1]:
import tensorflow as tf

In [2]:
a=tf.constant(80000)
b=tf.constant(900000000)
c=a+b
print(c)

tf.Tensor(900080000, shape=(), dtype=int32)


In [4]:
print(c.numpy())

900080000


In [9]:
x=tf.Variable([[248,124,146],
              [882,398,482]])

y=tf.constant([122,124,128])

print(x*y)

tf.Tensor(
[[ 30256  15376  18688]
 [107604  49352  61696]], shape=(2, 3), dtype=int32)


In [10]:
x=tf.transpose(x)
print(x)

tf.Tensor(
[[248 882]
 [124 398]
 [146 482]], shape=(3, 2), dtype=int32)


Computational Graph: TensorFlow uses a computational graph to represent and execute operations. Each operation corresponds to a node in the graph, and edges represent the data flow (tensors).

In [11]:
import torch

In [12]:
a=torch.tensor([122,124,126])
b=torch.tensor([442,444,446])

print(a+b)

print(b-a)

tensor([564, 568, 572])
tensor([320, 320, 320])


In [13]:
print(a*b)

tensor([53924, 55056, 56196])


In a static graph that Tensorflow uses, the entire computation process is defined before execution. You first define the graph, then run the session to compute the results.

Dynamic graphs are defined and executed at runtime. This is the approach used by PyTorch. Every time a forward pass is made, a new graph is created on the fly.

In [14]:
a.shape

torch.Size([3])

In [17]:
tensor1=torch.ones(4,4)
print(tensor1)
tensor2=torch.zeros(4,4)
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [18]:
print(torch.cat([tensor1,tensor2]))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [19]:
print(tensor1.numpy())

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
print(tensor1+tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [21]:
print(tensor1*tensor2)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
